version: '2'
services:
    de-ondics-sso-mysql:
      image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/de-ondics-sso-mysql:1.0
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
    
    de-ondics-sso-app:
      image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/de-ondics-sso-app:1.0
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: de-ondics-sso-mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        #KEYCLOAK_USER: ${KEYCLOAK_USER}
        #KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        PROXY_ADDRESS_FORWARDING: true
        DB_VENDOR: MYSQL
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports: 
        - 8080
      labels:
        rap.host: sso
        rap.sso_disabled: "true"
      depends_on:
        - de-ondics-sso-mysql
    de-ondics-sso-protect-active:
      image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/de-ondics-sso-protect-active:1.0
      ports:
        - 80:80
        - 443:443
      environment:
        - SSO_URL=sso.${PLATFORM_DOMAIN}
        - SSO_CLIENT_ID=de-ondics-sso
        - SSO_CLIENT_SECRET=b8c2a7ec-948a-4439-9ffe-b466ed0888fa
        - PLATFORM_DOMAIN=${PLATFORM_DOMAIN}
        - SSO_VERIFY_SSL=${SSO_VERIFY_SSL}
      labels:
        platform_url: ${PLATFORM_DOMAIN}
        io.rancher.scheduler.global: 'true'
        io.rancher.container.pull_image: always
volumes:
  mysql_data:


