apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: de-ondics-siwiat-app
  name: de-ondics-siwiat-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: de-ondics-siwiat-app
    spec:
      containers:
      - env:
        - name: ENABLE_ENV_FILE
          value: "1"
        image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/de-ondics-siwiat-app:1.8
        name: de-ondics-siwiat-app
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/websites/ab/protected/modules
          name: siwiatmodules
        - mountPath: /var/www/html/websites/licence
          name: siwiatlicence
        - mountPath: /etc/localtime
          name: de-ondics-siwiat-app-claim2
          readOnly: true
        - mountPath: /etc/timezone
          name: de-ondics-siwiat-app-claim3
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: siwiatmodules
        persistentVolumeClaim:
          claimName: siwiatmodules
      - name: siwiatlicence
        persistentVolumeClaim:
          claimName: siwiatlicence
      - name: de-ondics-siwiat-app-claim2
        persistentVolumeClaim:
          claimName: de-ondics-siwiat-app-claim2
          readOnly: true
      - name: de-ondics-siwiat-app-claim3
        persistentVolumeClaim:
          claimName: de-ondics-siwiat-app-claim3
          readOnly: true
status: {}
