apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: calculator
  name: calculator
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: calculator
    spec:
      containers:
      - image: 0.0.0.0:5000/calc
        name: calculator
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
