apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-ondics-siwiat-admin
  name: db-ondics-siwiat-admin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db-ondics-siwiat-admin
    spec:
      containers:
      - env:
        - name: ETCD_SERVER
        - name: HOSTIPADDR
        - name: HOSTMACADDR
        - name: LICENCE_MANAGEMENT_SERVER
        image: scaleit-app-pool.ondics.de:5000/scaleit-app-pool/db-ondics-siwiat-admin:1.8
        name: db-ondics-siwiat-admin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
